services:
  - type: web
    name: test-render
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: AZURE_STORAGE_CONNECTION_STRING
        sync: false
      - key: AZURE_STORAGE_CONTAINER_NAME
        sync: false
